// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	input "github.com/jhmorais/anomalies-detection/internal/usecases/ports/input"

	mock "github.com/stretchr/testify/mock"

	output "github.com/jhmorais/anomalies-detection/internal/usecases/ports/output"
)

// AnomaliesUseCase is an autogenerated mock type for the AnomaliesUseCase type
type AnomaliesUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, result, parameters
func (_m *AnomaliesUseCase) Execute(ctx context.Context, result *output.AnomaliesOutput, parameters *input.ParametersAnomaliesInput) (*output.AnomaliesOutput, error) {
	ret := _m.Called(ctx, result, parameters)

	var r0 *output.AnomaliesOutput
	if rf, ok := ret.Get(0).(func(context.Context, *output.AnomaliesOutput, *input.ParametersAnomaliesInput) *output.AnomaliesOutput); ok {
		r0 = rf(ctx, result, parameters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*output.AnomaliesOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *output.AnomaliesOutput, *input.ParametersAnomaliesInput) error); ok {
		r1 = rf(ctx, result, parameters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAnomaliesUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewAnomaliesUseCase creates a new instance of AnomaliesUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAnomaliesUseCase(t mockConstructorTestingTNewAnomaliesUseCase) *AnomaliesUseCase {
	mock := &AnomaliesUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
